 'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'mysql'),
            'username' => env('DB_USERNAME', 'pma'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', null),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
